name: CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Build and push Docker image
        run: |
          docker build -t ocr-app .
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 774305614937.dkr.ecr.ap-south-1.amazonaws.com/ocr-app
          docker tag ocr-app:latest 774305614937.dkr.ecr.ap-south-1.amazonaws.com/ocr-app/ocr-app:latest
          docker push 774305614937.dkr.ecr.ap-south-1.amazonaws.com/ocr-app/ocr-app:latest
      - name: Deploy to ECS
        run: aws ecs update-service --cluster ocr-cluster-1 --service ocr-app-service --force-new-deployment
